config/routes.rb
Rails.application.routes.draw do
  
  get  "admin/users/:token/token/:command", to: "admin/users#token_command", as: :admin_user_token
  post "admin/users/:token/patch", to: "admin/users#patch", as: :admin_user_patch
  post "admin/users/:token/approve", to: "admin/users#approve_user", as: :admin_approve_user
  get  "admin/users/:token/wizard", to: "admin/users#wizard", as: :admin_user_wizard
  post "admin/users/:token/email", to: "admin/users#send_email", as: :admin_user_send_email
  post "admin/moderations/:token/resolved", to: "admin/moderations#resolved", as: :admin_moderation_resolved
  
  get  "admin/jotform", to: "admin/jotform#show"
  
  get  "admin/surveys/:id/test", to: "admin/surveys#test", as: :admin_survey_test
  get  "admin/surveys/:id/report", to: "admin/surveys#report", as: :admin_survey_report
  get  "admin/surveys/:id/notes/new", to: "admin/surveys#new_note", as: :new_admin_survey_note
  get  "admin/surveys/:id/duplicate", to: "admin/surveys#duplicate", as: :admin_survey_duplicate
  post "admin/notes(/:id/patch)", to: "admin/notes#patch", as: :admin_note_patch
  post "admin/survey_groups/:id/patch", to: "admin/survey_groups#patch", as: :admin_survey_group_patch
  post "admin/survey_questions/:id/patch", to: "admin/survey_questions#patch", as: :admin_survey_question_patch

  get "login/:token", to: "home#login", as: :login
  get "logout", to: "home#logout", as: :logout
  get "send_magic_link", to: "home#send_magic_link", as: :send_magic_link
  get "unsubscribe/:token", to: "home#unsubscribe", as: :unsubscribe
  get "user_search", to: "admin/users#search", as: :user_search
  
  # yes, some of these params are optional because js will add the params
  get  "survey/live/:token", to: "survey_invites#live_view", as: :survey_live_view
  get  "survey/results/:token", to: "survey_invites#show_results", as: :survey_show_results
  post "survey/patch/:token(/:id)", to: "survey_invites#patch", as: :survey_patch
  get  "survey(/:token)(/:survey_question_id)", to: "survey_invites#show", as: :survey
  post "admin/survey_invites/:id/patch", to: "admin/survey_invites#patch", as: :admin_survey_invite_patch
  get  "take_survey/:survey_token", to: "survey_invites#new", as: :new_take_survey
  post "take_survey/:survey_token", to: "survey_invites#create", as: :take_survey

  delete  "survey/votes/:token/:survey_question_id", to: "survey_invites#delete_votes", as: :survey_delete_votes
  
  namespace :admin do
    resources :users, param: :token, only: [:index, :show]
    resources :surveys do
      resources :survey_invites, only: [:new, :create]
      resources :notes, only: [:index, :create, :destroy]
      resources :survey_groups, only: [:new, :create, :edit, :update, :destroy] do
        resources :survey_questions, only: [:new, :create, :edit, :update, :destroy]
      end
    end
    resources :moderations, param: :token, only: [:index, :show, :new, :create]
    resources :violations
  end

  resources :users, param: :token, only: [:show, :edit, :update]
  resources :moderation_assessment, param: :token, only: [:index, :show], path: "m"

  root to: "home#index"
end

app/models/survey.rb
class Survey < ActiveRecord::Base
  include Operation::SurveyHelper

  has_many :survey_groups, dependent: :destroy
  has_many :survey_invites, dependent: :destroy
  
  has_many :survey_questions, through: :survey_groups
  has_many :notes, through: :survey_groups
  has_many :users, through: :survey_invites

  has_secure_token

  def ordered_groups
    survey_groups.order(position: :asc)
  end
  def ordered_note_groups
    survey_groups.order(position: :asc).select do |group|
      group.notes.count > 0 || group.survey_questions.count == 0
    end
  end

  def ordered_notes
    ordered_groups.collect(&:ordered_notes).flatten
  end
  def ordered_questions
    ordered_groups.collect(&:ordered_questions).flatten
  end

  def last_updated_note_timestamp
    # group color may have been updated
    note = notes.order(updated_at: :asc).last
    group = survey_groups.order(updated_at: :asc).last
    note.updated_at > group.updated_at ? note.updated_at : group.updated_at
  end

  # for use in getting questions and prev and next positions
  STATES = {
    seeking: 10,
    current_position_found: 11,
    first_question_found: 12,
    last_question_found: 13,
    seeking_question: 14,
    seeking_non_note: 15,
    page_found: 20,
    first_page_found: 21,
    second_page_found: 22,
    seeking_second_page: 30,
    non_note_found: 31,
    note_found: 32,
    last_note_found: 33,
    finished: 40
  }

  def get_survey_questions(survey_question)
    state = STATES[:seeking]
    ordered_questions.select do |sq|
      state = STATES[:first_question_found] if sq.id == survey_question.id
      next if STATES[:seeking] == state
      state = STATES[:last_question_found] if sq.new_page? || sq.note?
      STATES[:last_question_found] != state
    end
  end

  def get_notes(survey_question)
    state = STATES[:seeking]
    ordered_questions.collect do |sq|
      state = STATES[:first_question_found] if sq.id == survey_question.id
      next if STATES[:seeking] == state
      state = STATES[:last_question_found] if !sq.note?
      next if STATES[:last_question_found] == state
      sq.note
    end.compact
  end

  def last_note_survey_group
    default_group = survey_groups.first
    return default_group if ordered_notes.blank?
    Note.where(survey_group_id: survey_groups.collect(&:id)).order(updated_at: :asc).last.survey_group
  end

  def fixup_positions
    ordered_groups.each_with_index do |group, i|
      group.update position: i if group.position != i
      group.ordered_notes.each_with_index do |note, j|
        note.update position: j if note.position != j
      end
      group.ordered_questions.each_with_index do |question, j|
        question.update position: j if question.position != j
      end
    end
  end

  def max_z_index
    ordered_notes.map(&:z_index).compact.max || 0
  end

  def clean_up_notes_z_index
    notes.order(z_index: :asc).each_with_index do |note, i|
      note.update(z_index: i+1) if note.z_index != i+1
    end
  end

  # ------------------------------------------------------------------------
  ######
  # PREV
  #####
  def get_prev_page_start_question_id(survey_question)
    # | starting from the last question
    # |
    # V
    # question      <- skip
    # question      <- skip
    # question      <- current group/question position (skip)
    # new_page/note <- update question_position and start looking for next page/non-note
    # question/note <- update question_position
    # question/note <- update question_position
    # new_page      <- break if new_page or non-note
    question_id = -1
    state = STATES[:seeking]
    ordered_questions.reverse.each do |sq|
      case state
      when STATES[:seeking]
        next unless sq.id == survey_question.id
        state = sq.note? ? STATES[:first_page_found] : STATES[:current_position_found]
      when STATES[:current_position_found]
        # assumption: previous question will be a note or new_page
        state = STATES[:first_page_found] if sq.new_page?
        state = STATES[:seeking_non_note] if sq.note?
      when STATES[:seeking_non_note]
        # when dealing with a group of notes
        break if !sq.note?
        question_id = sq.id
      when STATES[:first_page_found]
        next if sq.new_page?
        question_id = sq.id
        state = STATES[:seeking_second_page]
      when STATES[:seeking_second_page]
        break if sq.new_page? || sq.note?
        question_id = sq.id
      end
    end
    question_id
  end

  # ------------------------------------------------------------------------
  ######
  # NEXT
  #####
  def get_next_page_start_question_id(survey_question)
    # question      <- update question_position and break
    # new_page/note <- update and break if note, skip if new_page
    # question      <- skip
    # question      <- skip
    # question      <- current question position (skip)
    # ^             <- skip all previous questions
    # |
    # | start from the first question
    question_id = -1
    state = STATES[:seeking]
    ordered_questions.each do |sq|
      case state
      when STATES[:seeking]
        next unless sq.id == survey_question.id
        state = sq.note? ? STATES[:seeking_non_note] : STATES[:current_position_found]
      when STATES[:current_position_found]
        state = STATES[:page_found] if sq.new_page?
        question_id = sq.id
        state = STATES[:finished] if sq.note?
      when STATES[:page_found]
        next if sq.new_page?
        question_id = sq.id
        state = STATES[:finished]
      when STATES[:seeking_non_note]
        question_id = sq.id
        state = STATES[:finished] if !sq.note?
      end
      return question_id if STATES[:finished] == state
    end
    -1
  end

  # ------------------------------------------------------------------------

  def self.import_sticky_notes_tsv
    file = File.open "tmp/sticky-import.tsv"
    data = file.readlines.map(&:chomp)
    file.close

    # check first row for correct file format
    headers = data.shift
    correct_headers = [
      "Miro Board / Group",
      "Group",
      "Text",
      "Vision",
      "Mission",
      "Value",
      "Action",
      "Practice",
      "Being"
    ].join("\t")
    unless headers == correct_headers
      puts "header row = #{headers}" # first line is headers
      puts "should be  = #{correct_headers}"
      return
    end

    prev_group_number = new_survey = nil
    column = row = 0

    data.each do |line|
      url, group_number, text, is_vision, is_mission, is_value, is_action, is_practice, is_being  = line.split("\t")
      puts "line = #{line}"

      if group_number != prev_group_number
        new_survey = Operation::SurveyHelper::create_new_survey({
          name: "Survey for group #{group_number}",
          description: "Voting survey",
          create_initial_questions: true
        })
        raise "something went wrong with survey creation" unless new_survey
        prev_group_number = group_number
      end

      group_name = if "TRUE" == is_vision
        "Vision"
      elsif "TRUE" == is_mission
        "Mission"
      elsif "TRUE" == is_value
        "Value"
      elsif "TRUE" == is_action
        "Action"
      elsif "TRUE" == is_practice
        "Practice"
      elsif "TRUE" == is_being
        "Being"
      else
        raise "No group name found for #{line}"
      end

      new_survey_group = new_survey.survey_groups.where(name: group_name).first
      if new_survey_group.nil?
        new_survey_group = Operation::SurveyHelper::create_new_survey_group({
          survey: new_survey,
          name: group_name,
          description: "change this description",
          votes_max: 30,
          note_color: case group_name
          when "Vision"
            "#f7f7ad"
          when "Mission"
            "#c3edc0"
          when "Value"
            "#b3d4e8"
          else
            "#aaffaa"
          end
        })
        raise "something went wrong with group creation / find" unless new_survey_group
        new_survey_group.update position: new_survey.reload.survey_groups.count-1
        row = 0
      end

      if row > 4
        column += 1
        row = 0
      end
      left = (225 * (column - 1 + new_survey_group.position - 1)) + 20
      top = (225 * row) + 130
      row += 1

      new_note = Operation::SurveyHelper::create_new_note({
        survey_group: new_survey_group,
        text: text,
        coords: "#{left}px:#{top}px"
      })
      raise "something went wrong with note creation" unless new_note
      new_position = new_survey_group.reload.survey_questions.count-1
      new_note.update position: new_position
      new_note.survey_question.update position: new_position
    end
    # move the feedback group to the end
    survey.survey_groups.where(name: "Feedback").first.update position: survey.survey_groups.count
    survey.fixup_positions
  end

  # ------------------------------------------------------------------------

  def self.import_sticky_notes_csv(filename)
    file = File.open "tmp/#{filename}.csv"
    data = file.readlines.map(&:chomp)
    file.close

    survey_name = "Survey for group #{filename}"
    survey = Survey.find_by_name(survey_name) ||
    Operation::SurveyHelper::create_new_survey({
      name: survey_name,
      description: "Voting survey",
      create_initial_questions: true
    })
    raise "something went wrong with survey creation / find" unless survey

    column = -1
    row = 0
    group = nil

    data.each do |line|
      # line.gsub!(/^"(.+)"$/, '\1')
      puts "line = #{group ? group.name : "no group"}: #{line}"
      if line.match /Vision/
        assign_max_votes(group)
        group = create_group(survey, "Instructions for Vision / Mission", "")
        question = create_question(group, {question_type: "New Page"})
        question = create_question(group, {
          question_type: "Instructions",

app/controllers/admin/surveys_controller.rb
module Admin
  class SurveysController < AdminController
    layout "admin"
    before_action :signed_in_surveyor

    def index
      @surveys = Survey.order(id: :desc).all
      @token = form_authenticity_token
    end

    def new
      run Survey::Operation::Create::Present do |ctx|
        @form = ctx["contract.default"]
        render
      end
    end
    
    def create
      _ctx = run Survey::Operation::Create do |ctx|
        flash[:notice] = "Survey #{ctx[:model].name} was created"
        return redirect_to new_admin_survey_survey_group_url(survey_id: ctx[:model].id)
      end
    
      @form = _ctx["contract.default"]
      render :new, status: :unprocessable_entity
    end

    def duplicate
      _ctx = run Survey::Operation::Duplicate do |ctx|
        flash[:notice] = "Survey #{ctx[:existing_survey].name} was duplicated, showing the new survey"
        return redirect_to edit_admin_survey_url(ctx[:model].id)
      end
      
      flash[:error] = "Survey could not be duplicated, sorry about that"
      redirect_to admin_surveys_url
    end

    def show
      # show all questions in survey
      @survey = Survey.find(params[:id])
      @survey_groups = @survey.ordered_groups
      @token = form_authenticity_token
    end

    def edit
      _ctx = run Survey::Operation::Update::Present do |ctx|
        @form = ctx["contract.default"]
        render
      end
    end

    def update
      _ctx = run Survey::Operation::Update do |ctx|
        flash[:notice] = "Survey #{ctx[:model].name} updated"
        return redirect_to admin_survey_url(ctx[:model].id)
      end
    
      @form = _ctx["contract.default"]
      render :edit, status: :unprocessable_entity
    end

    def destroy
      run Survey::Operation::Delete do |ctx|
        flash[:notice] = "Survey deleted"
        return render json: { url: admin_surveys_url }
      end
      return head(:bad_request)
    end

    def new_note
      survey = Survey.find(params[:id])
      group = survey.last_note_survey_group
      # make like it came from a form:
      params[:survey_group_id] = group.id
      params.delete(:id)
      params[:note] = params
      run Note::Operation::Create, survey_group_id: group.id do |ctx|
        note = ctx[:model]
        return render json: { 
          model: note,
          color: note.group_color,
          group_name: note.group_name,
          patch_url: admin_note_patch_path(note),
          delete_url: admin_survey_note_path(note, survey_id: note.survey)
        }
      end
      return head(:bad_request)
    end

    def test
      _ctx = run Survey::Operation::Test, current_user: current_user, url: survey_url do |ctx|
        return redirect_to survey_url(token: ctx[:survey_invite].token)
      end
      flash[:error] = _ctx[:flash]
      return redirect_to admin_survey_url(ctx[:model].id)
    end

    def report
      @body_id = "survey"
      @token = form_authenticity_token
      @list = params[:list]
      @names = params[:names]
      @survey = Survey.find(params[:id])
      @survey_questions = {}
      @survey.ordered_questions.each do |sq|
        @survey_questions[sq.survey_group] ||= []
        @survey_questions[sq.survey_group].push sq
      end  
      @survey_invites = @survey.survey_invites
      @survey_invites_hash = {
        created: [],
        sent: [],
        opened: [],
        started: [],
        finished: []
      }
      @survey_invites.each do |si|
        @survey_invites_hash[:created].push(si) if si.is_created?
        @survey_invites_hash[:sent].push(si) if si.is_invite_sent?
        @survey_invites_hash[:opened].push(si) if si.is_opened?
        @survey_invites_hash[:started].push(si) if si.is_started?
        @survey_invites_hash[:finished].push(si) if si.is_finished? || si.finished_link_sent?
      end
    end
  end
end

app/views/admin/surveys/edit.html.haml
%h5 Editing Survey

= simple_form_for @form, as: :survey, url: admin_survey_path(@model.id), method: :patch do |f|
  .row
    .col= f.error_notification
  .row
    .col= f.input :name, placeholder: "Name", label: false
  .row
    .col= f.input :description, placeholder: "Description", label: false
  .row
    .col= f.input :liveview, as: :boolean, label: "Enable Liveview"
  .row
    .col= f.button :submit, "Update Survey", class: "btn-primary"
.row
  .col= link_to "Cancel", admin_surveys_path

app/views/admin/surveys/index.html.haml
%h5= (@surveys.empty? ? "No " : "") + "Existing Surveys"

.row
  .col
    - @surveys.each do |survey|
      %p.survey
        = link_to "edit", edit_admin_survey_path(survey)
        |
        = link_to "questions", admin_survey_path(survey)
        |
        = link_to "notes", admin_survey_notes_path(survey)
        |
        = link_to "invite", new_admin_survey_survey_invite_path(survey)
        |
        = link_to "report", admin_survey_report_path(survey)
        |
        = link_to "duplicate", admin_survey_duplicate_path(survey)
        |
        = link_to "test", admin_survey_test_path(survey)
        |
        = link_to "del", admin_survey_path(survey), data: { method: "delete", confirm: "Really delete #{survey.name}?", token: @token }
        %span.survey-name= survey.name

= link_to "New Survey", new_admin_survey_path(create_initial_questions: true), class: "btn btn-secondary"

app/views/admin/surveys/new.html.haml
%h5 New Survey

= simple_form_for @form, as: :survey, url: admin_surveys_path do |f|
  .row
    .col= f.error_notification
  .row
    .col= f.input :name, placeholder: "Name", label: false
  .row
    .col= f.input :description, placeholder: "Description", label: false
  .row
    .col= f.input :liveview, as: :boolean, label: "Enable Liveview"
  .row
    .col= f.button :submit, "Create Survey", class: "btn-primary"
.row
  .col= link_to "Cancel", admin_surveys_path

app/views/admin/surveys/report.html.haml
%h5= "Report for #{@survey.name}"

= link_to "Back", admin_survey_url(@survey), class: "user-back btn btn-secondary"

= cell(Survey::Cell::SurveyReportSummary, {invites: @survey_invites, invites_hash: @survey_invites_hash, list: @list, token: @token, names: @names})

#survey-container
  - @survey_questions.each_pair do |sg, asq|
    .survey-group-container.jumbotron.jumbotron-fluid{ id: "survey-group-#{sg.id}" }
      %h1.display-4.survey-group-name= sg.name
      %p.survey-group-description= sg.description
      %hr
      - if sg.voted?
        = cell(Survey::Cell::SurveyNoteReport, {survey_questions: asq, names: @names})
      - else
        #survey-questions-container
          - asq.each do |sq|
            = cell(Survey::Cell::SurveyReport, {survey_invites: @survey_invites, survey_question: sq, names: @names})

= link_to "Back", admin_survey_url(@survey)

app/views/admin/surveys/show.html.haml
%h5 Survey Groups and Questions

.row
  .col
    %p.survey-name
      = link_to "edit", edit_admin_survey_path(@survey)
      |
      = link_to "notes", admin_survey_notes_path(@survey)
      |
      = link_to "invite", new_admin_survey_survey_invite_path(@survey)
      |
      = link_to "report", admin_survey_report_path(@survey)
      |
      = link_to "duplicate", admin_survey_duplicate_path(@survey)
      |
      = link_to "test", admin_survey_test_path(@survey)
      |
      = link_to "del", admin_survey_path(@survey), data: { method: "delete", confirm: "Really delete survey?", token: @token }
      = "------"
      = "Survey: #{@survey.name}"

.row.survey-groups
  .col.sortable
    - @survey_groups.each do |sg|
      - position_url = admin_survey_group_patch_path(sg.id)
      .row.ui-state-default{ data: {url: position_url, position: sg.position, id: sg.id, token: @token} }
        .col
          .row
            .col
              %p.survey-group-name
                = link_to "edit", edit_admin_survey_survey_group_path(sg.id, survey_id: @survey.id)
                |
                = link_to "del", admin_survey_survey_group_path(sg.id, survey_id: @survey.id), data: { method: "delete", confirm: "Really delete group?" }
                = "----"
                = "Group: #{sg.name}"
          .row
            .col
              %table.survey-group.survey-questions.table.table-bordered.table-striped
                %thead
                  %tr
                    %th.action Actions
                    %th.question-type Question Type
                    %th.question Question
                    %th.answer-type Answer Type
                    %th.has-scale Scale?
                %tbody.sortable
                  - sg.ordered_questions.each do |sq|
                    - position_url = admin_survey_question_patch_path(sq.id)
                    - edit_url = edit_admin_survey_survey_group_survey_question_path(sq.id, survey_id: @survey.id, survey_group_id: sg.id)
                    - delete_url = admin_survey_survey_group_survey_question_path(sq.id, survey_id: @survey.id, survey_group_id: sg.id)
                    %tr.ui-state-default{ data: {url: position_url, position: sq.position, id: sq.id, token: @token} }
                      %td.actions
                        = link_to "edit", edit_url
                        |
                        = link_to "del", delete_url, data: { method: "delete", confirm: "Really delete question?" }
                      %td.question-type= sq.question_type
                      %td.question= sq.question
                      %td.answer-type= sq.answer_type
                      %td.has-scale= sq.has_scale? ? "Yes" : "No"
          .row
            .col
              - new_question_url = new_admin_survey_survey_group_survey_question_path(survey_id: @survey.id, survey_group_id: sg.id)
              = link_to "New Question", new_question_url, class: "btn btn-secondary"
.row
  .col
    = link_to "New Group", new_admin_survey_survey_group_path(@survey.id), class: "btn btn-secondary"
    %br
    = link_to "Back", admin_surveys_path