config/routes.rb
Rails.application.routes.draw do
  
  get  "admin/users/:token/token/:command", to: "admin/users#token_command", as: :admin_user_token
  post "admin/users/:token/patch", to: "admin/users#patch", as: :admin_user_patch
  post "admin/users/:token/approve", to: "admin/users#approve_user", as: :admin_approve_user
  get  "admin/users/:token/wizard", to: "admin/users#wizard", as: :admin_user_wizard
  post "admin/users/:token/email", to: "admin/users#send_email", as: :admin_user_send_email
  post "admin/moderations/:token/resolved", to: "admin/moderations#resolved", as: :admin_moderation_resolved
  
  get  "admin/jotform", to: "admin/jotform#show"
  
  get  "admin/surveys/:id/test", to: "admin/surveys#test", as: :admin_survey_test
  get  "admin/surveys/:id/report", to: "admin/surveys#report", as: :admin_survey_report
  get  "admin/surveys/:id/notes/new", to: "admin/surveys#new_note", as: :new_admin_survey_note
  get  "admin/surveys/:id/duplicate", to: "admin/surveys#duplicate", as: :admin_survey_duplicate
  post "admin/notes(/:id/patch)", to: "admin/notes#patch", as: :admin_note_patch
  post "admin/survey_groups/:id/patch", to: "admin/survey_groups#patch", as: :admin_survey_group_patch
  post "admin/survey_questions/:id/patch", to: "admin/survey_questions#patch", as: :admin_survey_question_patch

  get "login/:token", to: "home#login", as: :login
  get "logout", to: "home#logout", as: :logout
  get "send_magic_link", to: "home#send_magic_link", as: :send_magic_link
  get "unsubscribe/:token", to: "home#unsubscribe", as: :unsubscribe
  get "user_search", to: "admin/users#search", as: :user_search
  
  # yes, some of these params are optional because js will add the params
  get  "survey/live/:token", to: "survey_invites#live_view", as: :survey_live_view
  get  "survey/results/:token", to: "survey_invites#show_results", as: :survey_show_results
  post "survey/patch/:token(/:id)", to: "survey_invites#patch", as: :survey_patch
  get  "survey(/:token)(/:survey_question_id)", to: "survey_invites#show", as: :survey
  post "admin/survey_invites/:id/patch", to: "admin/survey_invites#patch", as: :admin_survey_invite_patch
  get  "take_survey/:survey_token", to: "survey_invites#new", as: :new_take_survey
  post "take_survey/:survey_token", to: "survey_invites#create", as: :take_survey

  delete  "survey/votes/:token/:survey_question_id", to: "survey_invites#delete_votes", as: :survey_delete_votes
  
  namespace :admin do
    resources :users, param: :token, only: [:index, :show]
    resources :surveys do
      resources :survey_invites, only: [:new, :create]
      resources :notes, only: [:index, :create, :destroy]
      resources :survey_groups, only: [:new, :create, :edit, :update, :destroy] do
        resources :survey_questions, only: [:new, :create, :edit, :update, :destroy]
      end
    end
    resources :moderations, param: :token, only: [:index, :show, :new, :create]
    resources :violations
  end

  resources :users, param: :token, only: [:show, :edit, :update]
  resources :moderation_assessment, param: :token, only: [:index, :show], path: "m"

  root to: "home#index"
end

app/models/violation.rb
class Violation < ActiveRecord::Base
  has_and_belongs_to_many :moderations
end

app/controllers/admin/violations_controller.rb
module Admin
  class ViolationsController < AdminController
    layout "admin"
    before_action :signed_in_moderator

    def index
      @token = form_authenticity_token
      @violations = Violation.all
    end

    def new
      @token = form_authenticity_token
      run Violation::Operation::Create::Present do |ctx|
        @form = ctx["contract.default"]
        render
      end
    end
    
    def create
      _ctx = run Violation::Operation::Create do |ctx|
        flash[:notice] = "Violation '#{ctx[:model].name}' created"
        return redirect_to admin_violations_url
      end
    
      @form = _ctx["contract.default"]
      render :new, status: :unprocessable_entity
    end

    def show
      redirect_to edit_admin_violation_url(params[:id])
    end

    def edit
      _ctx = run Violation::Operation::Update::Present do |ctx|
        @form = ctx["contract.default"]
        render
      end
    end

    def update
      _ctx = run Violation::Operation::Update do |ctx|
        flash[:notice] = "Violation '#{ctx[:model].name}' updated"
        return redirect_to admin_violations_url
      end
    
      @form = _ctx["contract.default"]
      render :edit, status: :unprocessable_entity
    end

    def destroy
      run Violation::Operation::Delete do |ctx|
        flash[:notice] = "Violation deleted"
        return render json: { url: admin_violations_url }
      end
      return head(:bad_request)
    end
  end
end

app/views/admin/violations/edit.html.haml
%h5 Edit Violation

= simple_form_for @form, as: :violation, url: admin_violation_path(@model.id), method: :patch do |f|
  .row
    .col= f.error_notification
  .row
    .col= f.input :name, placeholder: "Name", label: false
  .row
    .col= f.input :description, as: :text, placeholder: "Description", label: false
  .row
    .col= f.input :template, as: :text, placeholder: "Reply Template", label: false
  .row
    .col= f.button :submit, "Submit", class: "btn-primary"
.row
  .col= link_to "Cancel", admin_violations_path

app/views/admin/violations/index.html.haml
%h5= (@violations.empty? ? "No " : "") + "Possible Violations"

= link_to "New violation", new_admin_violation_path, class: "btn btn-primary"
= link_to "moderations", admin_moderations_path, class: "btn btn-secondary"

.row
  .col
    - @violations.each do |violation|
      %p.violation
        = link_to "edit", edit_admin_violation_path(violation)
        |
        = link_to "del", admin_violation_path(violation), data: { method: "delete", confirm: "Really delete #{violation.name}?", token: @token }
        %span.violation-name= violation.name

app/views/admin/violations/new.html.haml
%h5 New Violation

= simple_form_for @form, as: :violation, url: admin_violations_path do |f|
  .row
    .col= f.error_notification
  .row
    .col= f.input :name, placeholder: "Name", label: false
  .row
    .col= f.input :description, as: :text, placeholder: "Description", label: false
  .row
    .col= f.input :template, as: :text, placeholder: "Reply Template", label: false
  .row
    .col= f.button :submit, "Submit", class: "btn-primary"
.row
  .col= link_to "Cancel", admin_violations_path