config/routes.rb
Rails.application.routes.draw do
  
  get  "admin/users/:token/token/:command", to: "admin/users#token_command", as: :admin_user_token
  post "admin/users/:token/patch", to: "admin/users#patch", as: :admin_user_patch
  post "admin/users/:token/approve", to: "admin/users#approve_user", as: :admin_approve_user
  get  "admin/users/:token/wizard", to: "admin/users#wizard", as: :admin_user_wizard
  post "admin/users/:token/email", to: "admin/users#send_email", as: :admin_user_send_email
  post "admin/moderations/:token/resolved", to: "admin/moderations#resolved", as: :admin_moderation_resolved
  
  get  "admin/jotform", to: "admin/jotform#show"
  
  get  "admin/surveys/:id/test", to: "admin/surveys#test", as: :admin_survey_test
  get  "admin/surveys/:id/report", to: "admin/surveys#report", as: :admin_survey_report
  get  "admin/surveys/:id/notes/new", to: "admin/surveys#new_note", as: :new_admin_survey_note
  get  "admin/surveys/:id/duplicate", to: "admin/surveys#duplicate", as: :admin_survey_duplicate
  post "admin/notes(/:id/patch)", to: "admin/notes#patch", as: :admin_note_patch
  post "admin/survey_groups/:id/patch", to: "admin/survey_groups#patch", as: :admin_survey_group_patch
  post "admin/survey_questions/:id/patch", to: "admin/survey_questions#patch", as: :admin_survey_question_patch

  get "login/:token", to: "home#login", as: :login
  get "logout", to: "home#logout", as: :logout
  get "send_magic_link", to: "home#send_magic_link", as: :send_magic_link
  get "unsubscribe/:token", to: "home#unsubscribe", as: :unsubscribe
  get "user_search", to: "admin/users#search", as: :user_search
  
  # yes, some of these params are optional because js will add the params
  get  "survey/live/:token", to: "survey_invites#live_view", as: :survey_live_view
  get  "survey/results/:token", to: "survey_invites#show_results", as: :survey_show_results
  post "survey/patch/:token(/:id)", to: "survey_invites#patch", as: :survey_patch
  get  "survey(/:token)(/:survey_question_id)", to: "survey_invites#show", as: :survey
  post "admin/survey_invites/:id/patch", to: "admin/survey_invites#patch", as: :admin_survey_invite_patch
  get  "take_survey/:survey_token", to: "survey_invites#new", as: :new_take_survey
  post "take_survey/:survey_token", to: "survey_invites#create", as: :take_survey

  delete  "survey/votes/:token/:survey_question_id", to: "survey_invites#delete_votes", as: :survey_delete_votes
  
  namespace :admin do
    resources :users, param: :token, only: [:index, :show]
    resources :surveys do
      resources :survey_invites, only: [:new, :create]
      resources :notes, only: [:index, :create, :destroy]
      resources :survey_groups, only: [:new, :create, :edit, :update, :destroy] do
        resources :survey_questions, only: [:new, :create, :edit, :update, :destroy]
      end
    end
    resources :moderations, param: :token, only: [:index, :show, :new, :create]
    resources :violations
  end

  resources :users, param: :token, only: [:show, :edit, :update]
  resources :moderation_assessment, param: :token, only: [:index, :show], path: "m"

  root to: "home#index"
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/controllers/admin/roles_controller.rb
module Admin
  class RolesController < ApplicationController
    layout "admin"
    before_action :signed_in_user

    def index
      @search_url = admin_search_users_url
      @token = form_authenticity_token
    end

    def show
      @user = User.find(params[:id])
      @token = form_authenticity_token
    end

    def update_user
      _ctx = run User::Operation::Update, admin_name: current_user.name do |ctx|
        return render json: { user: ctx[:model].reload }
      end
        return head(:bad_request)
    end

    def approve_user
      _ctx = run User::Operation::Approve, admin: current_user do |ctx|
        flash[:notice] = "User approved -- thank you!"
        return render json: { url: admin_user_url(ctx[:model].id) }
      end
      return head(:bad_request)
    end

    private

    def init_vars
      
    end
  end
end

app/views/admin/roles/edit.html.haml
%h5= "Editing #{@model.name}"

= simple_form_for @form, as: :user, url: admin_user_path(@model.id), method: :patch do |f|
  .row
    .col= f.error_notification
  .row
    .col= f.input :email, placeholder: "Email", label: false
  .row
    .col= f.input :greeter, as: :boolean, label: "Greeter"
  .row
    .col= f.button :submit, "Update", class: "btn-primary"
.row
  .col= link_to "Cancel", admin_users_path

app/views/admin/roles/index.html.haml
%h5= (@users.empty? ? "No " : "") + "Existing Members"

%table.users.table.table-bordered.table-striped{ data: {url: @update_url, token: @token} }
  %thead
    %tr
      %th.name Name
      %th.greeter Greeter
      %th.status Status
      %th.meeting
        When?
        %br
        %span.tzinfo (GMT)
      %th.shadow Shadow
      %th.notes Notes
      %th.request Requested
  %tbody
    - @users.each do |u|
      %tr{ data: {url: admin_user_path(u.id), id: u.id}}
        %td.user-name= u.name
        %td.user-greeter= u.greeter_id ? u.greeter.name : ""
        %td.user-status= u.status
        %td.user-meeting-datetime.utc-time= u.when_timestamp ? u.when_timestamp.picker_datetime : nil
        %td.user-shadow= u.shadow_greeter_id ? u.shadow_greeter.name : nil
        %td.user-notes{ title: truncate(u.notes, length: 500, separator: ' ') }= u.notes_abbreviated
        %td.user-request= u.request_timestamp.picker_date

app/views/admin/roles/show.html.haml
%h3= @user.name
%p
  =link_to("👈 Back", admin_users_url, class: "user-back btn btn-secondary")
  = link_to("🙂 Profile", @user.profile_url, class: "user-profile-button btn btn-primary #{@user.profile_url ? "" : "hidden"}")
  = link_to("💬 Chat", @user.chat_url, class: "user-chat-button btn btn-primary #{@user.chat_url ? "" : "hidden"}")

%table.user.table.table-bordered.table-striped{ data: {url: admin_users_url, token: @token, id: @user.id } }
  %tbody
    %tr
      %td.header Greeter
      %td.user-greeter{ data: {greeter_id: @user.greeter_id.to_s} }
        = link_to((@user.greeter_id ? @user.greeter.name : "I will greet"), "#")
    %tr
      %td.header Email
      %td.user-email= link_to @user.email, "mailto:#{ @user.email }"
    %tr
      %td.header Status
      %td.user-status
        %select
          - User.get_status_options.each do |o|
            - selected = (o == @user.status ? "selected" : nil)
            %option{ selected: selected }= o
    %tr
      %td.header.meeting
        When
        %br
        %span.tzinfo (GMT)
      %td.user-meeting-datetime
        - datetime = @user.when_timestamp ? @user.when_timestamp.picker_datetime : nil
        %input.datetime-picker.utc-time{ type: "text", value: datetime }
    %tr
      %td.header Shadow
      %td.user-shadow{ data: {greeter_id: @user.shadow_greeter_id.to_s} }
        = link_to((@user.shadow_greeter_id? ? @user.shadow_greeter.name : "I will shadow"), "#")
    %tr
      %td.header Notes
      %td.user-notes
        %textarea{ cols: "40" }= @user.notes
        %span.save-status
    %tr
      %td.header Questions
      %td.user-questions
        %ol
          - @user.questions_responses.split(" -:- ").each do |qna|
            - q, a = *qna.split("\\")
            %li
              %span.question= q
              %br
              %span.answer= a
        - if @user.status == "Pending"
          - url = @user.email.blank? ? "#" : admin_approve_user_path(@user.id)
          = link_to "Approve", url, class: "btn btn-primary user-approve"
          = link_to "Reject", "#", class: "btn btn-warning user-reject"
          .lds-hourglass#spinner
          %span.progress-message Working ...
    %tr
      %td.header ChangeLog
      %td.change-log!= @user.change_log ? @user.change_log.gsub("\n","<br>") : "(no changes)"