config/routes.rb
Rails.application.routes.draw do
  
  get  "admin/users/:token/token/:command", to: "admin/users#token_command", as: :admin_user_token
  post "admin/users/:token/patch", to: "admin/users#patch", as: :admin_user_patch
  post "admin/users/:token/approve", to: "admin/users#approve_user", as: :admin_approve_user
  get  "admin/users/:token/wizard", to: "admin/users#wizard", as: :admin_user_wizard
  post "admin/users/:token/email", to: "admin/users#send_email", as: :admin_user_send_email
  post "admin/moderations/:token/resolved", to: "admin/moderations#resolved", as: :admin_moderation_resolved
  
  get  "admin/jotform", to: "admin/jotform#show"
  
  get  "admin/surveys/:id/test", to: "admin/surveys#test", as: :admin_survey_test
  get  "admin/surveys/:id/report", to: "admin/surveys#report", as: :admin_survey_report
  get  "admin/surveys/:id/notes/new", to: "admin/surveys#new_note", as: :new_admin_survey_note
  get  "admin/surveys/:id/duplicate", to: "admin/surveys#duplicate", as: :admin_survey_duplicate
  post "admin/notes(/:id/patch)", to: "admin/notes#patch", as: :admin_note_patch
  post "admin/survey_groups/:id/patch", to: "admin/survey_groups#patch", as: :admin_survey_group_patch
  post "admin/survey_questions/:id/patch", to: "admin/survey_questions#patch", as: :admin_survey_question_patch

  get "login/:token", to: "home#login", as: :login
  get "logout", to: "home#logout", as: :logout
  get "send_magic_link", to: "home#send_magic_link", as: :send_magic_link
  get "unsubscribe/:token", to: "home#unsubscribe", as: :unsubscribe
  get "user_search", to: "admin/users#search", as: :user_search
  
  # yes, some of these params are optional because js will add the params
  get  "survey/live/:token", to: "survey_invites#live_view", as: :survey_live_view
  get  "survey/results/:token", to: "survey_invites#show_results", as: :survey_show_results
  post "survey/patch/:token(/:id)", to: "survey_invites#patch", as: :survey_patch
  get  "survey(/:token)(/:survey_question_id)", to: "survey_invites#show", as: :survey
  post "admin/survey_invites/:id/patch", to: "admin/survey_invites#patch", as: :admin_survey_invite_patch
  get  "take_survey/:survey_token", to: "survey_invites#new", as: :new_take_survey
  post "take_survey/:survey_token", to: "survey_invites#create", as: :take_survey

  delete  "survey/votes/:token/:survey_question_id", to: "survey_invites#delete_votes", as: :survey_delete_votes
  
  namespace :admin do
    resources :users, param: :token, only: [:index, :show]
    resources :surveys do
      resources :survey_invites, only: [:new, :create]
      resources :notes, only: [:index, :create, :destroy]
      resources :survey_groups, only: [:new, :create, :edit, :update, :destroy] do
        resources :survey_questions, only: [:new, :create, :edit, :update, :destroy]
      end
    end
    resources :moderations, param: :token, only: [:index, :show, :new, :create]
    resources :violations
  end

  resources :users, param: :token, only: [:show, :edit, :update]
  resources :moderation_assessment, param: :token, only: [:index, :show], path: "m"

  root to: "home#index"
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :greeter, class_name: "User", optional: true
  belongs_to :shadow_greeter, class_name: "User", optional: true
  has_many :survey_invites, dependent: :destroy
  has_many :surveys, through: :survey_invites
  has_secure_token
  rolify

  def revoke_tokens
    # update(token: nil) # NB: don't nil token, it breaks views
    update(session_token: nil)
  end
  def generate_tokens
    update(token: User.generate_unique_secure_token) if token.nil?
    update(session_token: SecureRandom.urlsafe_base64) if session_token.nil?
  end
  def regenerate_tokens
    revoke_tokens
    generate_tokens
  end

  def questions_responses_array
    (questions_responses || []).split(" -:- ").collect { |qna| qna.split("\\") }
  end

  def lock
    update locked: true
  end
  def unlock
    update locked: false
  end

  def notes_abbreviated
    notes ? "#{notes[0..16]}#{notes_ellipsis(16)}" : nil
  end

  def notes_ellipsis(len)
    notes.length > len ? "..." : nil
  end

  def get_status_options
    {
      "Pending": [
        "Clarification Needed"
      ],
      "Clarification Needed": [
        "Request Declined",
        "Scheduling Zoom"
      ],
      "Request Declined": [
        "Pending"
      ],
      "Scheduling Zoom": [
        "Zoom Scheduled",
        "Zoom Declined (completed)",
        "Chat Done (completed)",
        "No Response (completed)"
      ],
      "Zoom Scheduled": [
        "Zoom Done (completed)",
        "Zoom Declined (completed)",
        "Chat Done (completed)",
        "No Response (completed)",
        "Scheduling Zoom"
      ],
      "Zoom Done (completed)":[
        "Scheduling Zoom"
      ],
      "Zoom Declined (completed)":[
        "Scheduling Zoom"
      ],
      "Chat Done (completed)":[
        "Scheduling Zoom"
      ],
      "No Response (completed)":[
        "Scheduling Zoom"
      ]
    }[status.to_sym].insert(0, status)
  # handle older greetings:
  rescue NoMethodError
    return [
      "Pending",
      "Rejected",
      "Joined!",
      "Clarifying email sent",
      "1st email Sent",
      "2nd email Sent",
      "Emailing",
      "No Response",
      "Rescheduling",
      "Follow Up",
      "Will Call",
      "Greet Scheduled",
      "Declined",
      "Welcomed",
      "Posted Intro",
      "Completed",
      "Scheduling Zoom",
      "Zoom Scheduled",
      "Zoom Declined (completed)",
      "Chat Done (completed)",
      "No Response (completed)",
      "Zoom Done (completed)"
    ]
  end

  def self.import_users
    file = File.open "tmp/import.tsv"
    data = file.readlines.map(&:chomp)
    file.close

    # check first row for correct file format
    header = data.shift
    headers = header.split("\t").collect(&:to_sym)

    data.each do |line|
      values = line.split("\t")

      model = {}
      headers.each_with_index do |head, i|
        model[head] = case head
        when :opt_out
          values[i].present?
        when :join_timestamp
          if values[i].present?
            ts = values[i].split("/")
            "20#{ts[2]}/#{ts[0]}/#{ts[1]}"
          end
        else
          values[i]
        end
      end
      model.compact!

      if model[:first_name] || model[:last_name]
        model[:name] = "#{model[:first_name]} #{model[:last_name]}"
      end
      id = model[:member_id]
      model[:profile_url] = "https://emergent-commons.mn.co/members/#{id}"
      model[:chat_url] = "https://emergent-commons.mn.co/chats/new?user_id=#{id}"

      user = find_by_member_id(id)

      if user
        puts "-------------------------------------------------\nupdating #{user.inspect} to #{model}"
        user.update model
      # else -- no because member might be in db w/o member_id
      #   puts "creating #{model}"
      #   User.create model
      end
    end
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < ApplicationController
    layout "greeter"
    before_action :signed_in_greeter

    # ------------------------------------------------------------------------

    def index
      date = Time.now - 3.months
      users = User
        .order(request_timestamp: :desc)
        .where('request_timestamp >= ? OR greeter_id = ?', date, current_user.id)
      @users = map_users_for_index_view(users)
      @update_url = admin_users_url
      @token = form_authenticity_token
    end

    # ------------------------------------------------------------------------

    def show
      @user = User.find_by_token(params[:token])
      @status_options = @user.get_status_options
      @token = form_authenticity_token
      @body_class = "user-wizard"
    end
    
    # ------------------------------------------------------------------------

    def wizard
      @user = User.find_by_token(params[:token])
      case params[:status]
      when "clarification-needed"
        @user.update status: "Clarification Needed"
        return redirect_to admin_user_wizard_url(token: @user.token)
      when "request-declined"
        @user.update status: "Request Declined"
        return redirect_to admin_user_wizard_url(token: @user.token)
      when "scheduling-zoom"
        @user.update status: "Scheduling Zoom"
        flash[:notice] = "User successfully transitioned to scheduling zoom"
        return redirect_to admin_user_wizard_url(token: @user.token)
      when "zoom-scheduled"
        @user.update status: "Zoom Scheduled"
        flash[:notice] = "User successfully transitioned to zoom scheduled"
        return redirect_to admin_user_wizard_url(token: @user.token)
      when "zoom-done"
        @user.update status: "Zoom Done (completed)"
        return redirect_to admin_user_wizard_url(token: @user.token)
      when "chat-done"
        @user.update status: "Chat Done (completed)"
        return redirect_to admin_user_wizard_url(token: @user.token)
      when "zoom-declined"
        @user.update status: "Zoom Declined (completed)"
        return redirect_to admin_user_wizard_url(token: @user.token)
      when "no-resposne"
        @user.update status: "No Response (completed)"
        return redirect_to admin_user_wizard_url(token: @user.token)
      end
      @token = form_authenticity_token
      @body_class = "user-wizard"
    end

    # ------------------------------------------------------------------------

    def patch
      _ctx = run User::Operation::Patch, admin_name: current_user.name do |ctx|
        return render json: { 
          model: ctx[:model].reload,
          status_options: ctx[:model].get_status_options
        }
      end
      return head(:bad_request)
    end

    # ------------------------------------------------------------------------

    def approve_user
      @user = User.find_by_token(params[:token])
      _ctx = run User::Operation::Approve, admin: current_user do |ctx|
        flash[:notice] = "User scheduled for approval, shouldn't take longer than 30 minutes to be reflected in EC"
      end
      redirect_to admin_user_wizard_url(token: @user.token)
    end

    # ------------------------------------------------------------------------

    def send_email
      user = User.find_by_token(params[:token])
      email_user = Rails.env.production? ? user : current_user
      UserMailer.with({
        user: email_user,
        subject: params[:subject],
        body: params[:body]
      }).send_greeter_invite_email.deliver_now
      flash[:notice] = "Email sent to #{user.name}"
      return render json: {
        url: admin_user_wizard_url(token: user.token)
      }
    end

    # ------------------------------------------------------------------------

    def search
      params.permit(:q, :source, user: {}) # TODO: why is an empty user hash being received?
      name = params[:q].chomp.gsub('  ', ' ').gsub(/[^a-zA-Z ]/, '')
      name = "%#{name}%" # do this outside the LIKE statement
      source = params[:source]
      
      like_clause = (Rails.env.staging? || Rails.env.staging?) ?
      "name ILIKE '#{name}'" :
      "UPPER(name) LIKE '#{name.upcase}'"

      users = User.where(like_clause).order(last_name: :asc)
      users = case source
      when "greeter"
        map_users_for_index_view(users)
      else
        users.collect {|u| [u.id, u.name]}
      end
      render json: { users: users }
    end

    # ------------------------------------------------------------------------

    def token_command
      # params.permit(:command)
      user = User.find_by_token(params[:token])
      case params[:command]
      when "generate"
        user.generate_tokens
        flash[:notice] = "Tokens generated"
      when "regenerate"
        user.regenerate_tokens
        flash[:notice] = "Tokens regenerated"
      when "revoke"
        user.revoke_tokens
        flash[:notice] = "Tokens revoked"
      when "toggle_lock"
        user.locked? ? user.unlock : user.lock
        flash[:notice] = "User account #{user.locked? ? nil : "un"}locked"
      else
        flash[:error] = "Unknown action requested #{params[:command]}"
      end
      redirect_to admin_user_url(token: user.token)
    end

    # ------------------------------------------------------------------------

    private

    def map_users_for_index_view(users)
      users.map do |u|
        css_class = []
        css_class.push("pending") unless u.joined? && u.greeter_id
        css_class.push("clarification") if "Clarification Needed" == u.status
        css_class.push("declined") if "Request Declined" == u.status
        css_class.push("scheduling") if "Scheduling Zoom" == u.status
        css_class.push("scheduled") if "Zoom Scheduled" == u.status
        css_class.push("complete") if u.status.index("(completed)")
        done = u.status.match /completed/
        {
          "name": u.name,
          "greeter": u.greeter ? u.greeter.name : nil,
          "greeter_id": u.greeter_id,
          "status": u.status,
          "when": u.when_timestamp ? u.when_timestamp.picker_datetime : nil,
          "notes": u.notes_abbreviated,
          "truncated": u.notes ? u.notes.truncate(500, separator: ' ') : nil,
          "joined": u.join_timestamp ? u.join_timestamp.picker_date : nil,
          "request": u.request_timestamp ? u.request_timestamp.picker_date : nil,
          "url": done ? admin_user_url(token: u.token) : admin_user_wizard_url(token: u.token),
          "token": u.token,
          "id": u.id,
          "css_class": css_class.join(" ")
        }
      end
    end
  end
end

app/controllers/greeters/users_controller.rb
module Greeters
  class UsersController < ApplicationController
    layout "greeters"
    before_action :signed_in_user

    def index
      date = Time.now - 2.months
      @users = User.order(request_timestamp: :desc).where('request_timestamp >= ?', date)
      @update_url = admin_users_url
      @token = form_authenticity_token
    end

    def show
      @user = User.find(params[:id])
      @token = form_authenticity_token
    end

    def update_user
      _ctx = run User::Operation::Update, admin_name: current_user.name do |ctx|
        return render json: { user: ctx[:model].reload }
      end
        return head(:bad_request)
    end

    def approve_user
      _ctx = run User::Operation::Approve, admin: current_user do |ctx|
        flash[:notice] = "User approved -- thank you!"
        return render json: { url: admin_user_url(ctx[:model].id) }
      end
      return head(:bad_request)
    end

    private

    def init_vars
      
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout "application"
  before_action :signed_in_greeter

  def show
    @user = current_user
  end

  def edit
    run User::Operation::Update::Present do |ctx|
      @form = ctx["contract.default"]
      render
    end
  end

  def update
    _ctx = run User::Operation::Update do |ctx|
      flash[:notice] = "User profile updated"
      return redirect_to user_url(token: ctx[:model].token)
    end
  
    flash[:error] = "Unable to update profile, please correct errors"
    @form = _ctx["contract.default"]
    render :edit, status: :unprocessable_entity
  end
end

app/views/admin/users/edit.html.haml
%h5= "Editing #{@model.name}"

= simple_form_for @form, as: :user, url: admin_user_path(@model.id), method: :patch do |f|
  .row
    .col= f.error_notification
  .row
    .col= f.input :email, placeholder: "Email", label: false
  .row
    .col= f.input :greeter, as: :boolean, label: "Greeter"
  .row
    .col= f.button :submit, "Update", class: "btn-primary"
.row
  .col= link_to "Cancel", admin_users_path

app/views/admin/users/index.html.haml
%h5 Greeter View

.row
  .col.controls
    %input#show-all-greetings{ type: "checkbox" }
    %label{ for: "show-all-greetings" } Show all greetings

.row
  .col{ data: {url: user_search_path} }
    %table.users.table.table-bordered.table-striped
      %thead
        %tr
          %th.name Name
          %th.greeter Greeter
          %th.status Status
          %th.meeting
            Zoom Meeting
            %br
            %span.tzinfo (GMT)
          %th.notes Notes
          %th.joined Joined
          %th.request Requested
      %tbody
        - @users.each do |u|
          - dataset = {url: u[:url], id: u[:id], status: u[:status], greeter_id: u[:greeter_id] }
          %tr{ class: u[:css_class], data: dataset }
            %td.user-name= u[:name]
            %td.user-greeter= u[:greeter]
            %td.user-status= u[:status]
            %td.user-meeting-datetime.utc-time= u[:when]
            %td.user-notes{ title: u[:truncated] }= u[:notes]
            %td.user-joined= u[:joined]
            %td.user-request= u[:request]
      %tfoot
        %tr
          %td{ colspan: 7} No pending requests to join and you have no active greetings

app/views/admin/users/show.html.haml
- dataset = {url: admin_user_patch_url(token: @user.token), token: @token, id: @user.id, greeter_id: @user.greeter_id, status: @user.status, timestamp: @user.when_timestamp, shadow_id: @user.shadow_greeter_id}

- patch_url = admin_user_patch_path(token: @user.token)
- email_url = admin_user_send_email_path(token: @user.token)
- dataset = {url: patch_url, email_url: email_url, token: @token, id: @user.id, timestamp: @user.when_timestamp, greeter_id: @user.greeter_id}

.wizard{ data: dataset }
  .wizard-pane.jumbotron.user-summary
    %h2
      %span.user-name= @user.name
      %span= @user.locked? ? " (locked)" : nil
    %p.user-greeter
      %strong Greeter:
      = @user.greeter_id ? @user.greeter.name : "(nobody)"
    %p.user-email
      %strong Email address:
      = link_to @user.email, "mailto:#{@user.email}"
    %p.user-greeting-date.utc-time
      %strong Greeting on:
      = @user.when_timestamp ? @user.when_timestamp.picker_datetime : "(no date set)"

    = link_to("👈 Back", admin_users_url, class: "user-back btn btn-secondary")
    = link_to("🙂 Profile", @user.profile_url, class: "user-profile-button btn btn-primary", target: "_blank") if @user.profile_url
    = link_to("💬 Chat", @user.chat_url, class: "user-chat-button btn btn-primary", target: "_blank") if @user.chat_url

    %h5 Status:
    .user-status
      %select
        - @status_options.each do |o|
          - selected = (o == @user.status ? "selected" : nil)
          %option{ selected: selected }= o
    .user-notes
      %h5 Notes
      %p (Record anything here that a greeter might need to know, in case you need to turn over this greeting)
      %textarea= @user.notes
      %span.save-status


  %br
  = link_to "Show or Hide answers to questions", "#", class: "reveal-answers padded #{@user.joined? ? nil : "hidden"}"
  .wizard-pane.jumbotron.user-questions{ class: @user.joined? ? "hidden" : "" }
    %h2 Questions and Answers
    %ol.questions-and-answers
      - @user.questions_responses_array.each do |q, a|
        %li
          %span.question= q
          %br
          %span.answer= a


  %br
  = link_to "Show or Hide change log", "#", class: "reveal-change-log padded #{@user.joined? ? nil : "hidden"}"
  .wizard-pane.jumbotron.change-log.hidden
    != @user.change_log ? @user.change_log.gsub("\n","<br>") : "(no changes)"


  .wizard-pane.jumbotron.admin.opt.hidden
    %h5 Admin Use Only!
    = link_to "Generate Tokens", admin_user_token_url(token: @user.token, command: "generate")
    |
    = link_to "Regenerate Tokens", admin_user_token_url(token: @user.token, command: "regenerate")
    |
    = link_to "Revoke Tokens", admin_user_token_url(token: @user.token, command: "revoke")
    |
    - command_text = "#{@user.locked? ? "Unlock" : "Lock"} User"
    = link_to command_text, admin_user_token_url(token: @user.token, command: "toggle_lock")

app/views/admin/users/wizard.html.haml
- patch_url = admin_user_patch_path(token: @user.token)
- email_url = admin_user_send_email_path(token: @user.token)
- dataset = {url: patch_url, email_url: email_url, token: @token, id: @user.id, timestamp: @user.when_timestamp, greeter_id: @user.greeter_id}
- pending = !@user.joined?

.wizard{ data: dataset }
  .wizard-pane.jumbotron.wizard-links
    %h2.user-name= @user.name
    %p.user-status= "Status: #{@user.status}"
    %p= "Email address: #{@user.email}"
    %p.user-greeter
      Greeter:
      - link_text = @user.greeter_id ? @user.greeter.name : "I want to greet"
      = link_to link_text, "#"
    = link_to("👈 Back", admin_users_url, class: "user-back btn btn-secondary")
    = link_to("🙂 Profile", @user.profile_url, class: "user-profile-button btn btn-primary", target: "_blank") if @user.profile_url
    = link_to("💬 Chat", @user.chat_url, class: "user-chat-button btn btn-primary", target: "_blank") if @user.chat_url


  -# make answers to questions available throughout the process
  = link_to "Show or Hide answers to questions", "#", class: "reveal-answers padded"
  .wizard-pane.jumbotron.user-questions{ class: pending ? "" : "hidden" }
    %h2 Questions and Answers
    %ol.questions-and-answers
      - @user.questions_responses_array.each do |q, a|
        %li
          %span.question= q
          %br
          %span.answer= a
    - if pending
      .approval-buttons
        - url = admin_approve_user_path(token: @user.token)
        = button_to "Answers Are Acceptable (Approve)", url, class: "btn btn-success user-approve"
        - url = admin_user_wizard_path(token: @user.token, status: "clarification-needed")
        = link_to "Answers Need Clarification", url, class: "btn btn-warning user-clarify"

  - unless "Clarification Needed" == @user.status
    -# greeter can compose message to send
    -# button for "Meeting Scheduled" to go to next page
    .wizard-pane.jumbotron.action
      %h2 Select action for this new member:
      = link_to "Compose Email", "#", class: "btn btn-primary action-send-email"
      - url = admin_user_wizard_path(token: @user.token, status: "zoom-scheduled")
      = link_to "Enter Greeting Date", url, class: "btn btn-primary action-schedule-zoom"
      = link_to "Complete / Done", "#", class: "btn btn-success action-complete"
      %hr
      .user-email.hidden
        %h2 Scheduling a Zoom Greeting via Email
        %p.no-margin= "To: #{@user.name}"
        %p
          To email:
          %span.email-address= link_to @user.email, "mailto:#{@user.email}"
        %input.email-subject.form-control{ placeholder: "Subject" }
        %textarea.email-body.form-control{ placeholder: "Body of greeting" }
        %p You can choose from these templates or compose your own email.
        .email-template-buttons.greeting Template buttons will be visible here
        .email-client
          %input#gmail{type: "radio", name: "email-client"}
          %label{for: "gmail"} Use GMail
          %input#outlook{type: "radio", name: "email-client"}
          %label{for: "outlook"} Use Outlook
          %input#yahoo{type: "radio", name: "email-client"}
          %label{for: "yahoo"} Use Yahoo
          %input#other{type: "radio", name: "email-client"}
          %label{for: "other"} Other
        = link_to "Launch Chosen Email Client", "#", class: "btn btn-primary email-send greeting"
        = link_to "Zoom Scheduled", admin_user_wizard_path(token: @user.token, status: "zoom-scheduled"), class: "btn btn-success"
      .complete.hidden
        %h2 Select Completion Type:
        - url = admin_user_wizard_path(token: @user.token, status: "zoom-done")
        = link_to "Zoom Done", url, class: "btn btn-success done"
        - url = admin_user_wizard_path(token: @user.token, status: "chat-done")
        = link_to "Chat Done", url, class: "btn btn-success done"
        - url = admin_user_wizard_path(token: @user.token, status: "zoom-declined")
        = link_to "Zoom Declined", url, class: "btn btn-success done"
        - url = admin_user_wizard_path(token: @user.token, status: "no-resposne")
        = link_to "No Response", url, class: "btn btn-success done"
      -# greeter can enter date and time for meeting
      -# button for "Meeting Done" to go to congratulatory completed page
      .user-meeting-datetime.hidden
        %h2 Date and time for your greeting
        %p When you get a response to your email, you can record the date and time here.
        - datetime = @user.when_timestamp ? @user.when_timestamp.picker_datetime : nil
        %input.datetime-picker.utc-time.form-control{ type: "text", value: datetime }

  - if @user.status.match /completed/
    -# give greeter a fun celebratory animation
    .wizard-pane.jumbotron.greeting-done
      - result = @user.status.match(/Done/) ? "greeting" : "attempting to greet"
      %h2= "Yay! Thanks for #{result} this new member"


  - if "Clarification Needed" == @user.status
    .wizard-pane.jumbotron.user-email
      %h2 Asking for Clarification
      %p.no-margin= "To: #{@user.name}"
      %p
        To email:
        %span.email-address= link_to @user.email, "mailto:#{@user.email}"
      %input.email-subject.form-control{ placeholder: "Subject" }
      %textarea.email-body.form-control{ placeholder: "Body of email" }
      %p You can choose from these templates or compose your own email.
      .email-template-buttons.clarification Template buttons will be visible here
      .email-client
        %input#gmail{type: "radio", name: "email-client"}
        %label{for: "gmail"} Use GMail
        %input#outlook{type: "radio", name: "email-client"}
        %label{for: "outlook"} Use Outlook
        %input#yahoo{type: "radio", name: "email-client"}
        %label{for: "yahoo"} Use Yahoo
        %input#email{type: "radio", name: "email-client"}
        %label{for: "email"} Other
      = link_to "Launch Email Client", "#", class: "btn btn-primary email-send clarification"
      .approval-buttons
        %p When you've received a response, or enough time has gone by, you can choose one of these actions:
        - url = admin_approve_user_path(token: @user.token)
        = button_to "Answers Are Acceptable (Approve)", url, class: "btn btn-success user-approve"
        - url = admin_user_wizard_path(token: @user.token, status: "request-declined")
        = link_to "Decline This Request", url, class: "btn btn-danger user-reject"


  .wizard-pane.jumbotron.user-notes
    %h2 Notes
    %p (Record anything here that a greeter might need to know, in case you need to turn over this greeting)
    %textarea= @user.notes
    %span.save-status


  = link_to "Show or Hide change log", "#", class: "reveal-change-log padded"
  .wizard-pane.jumbotron.change-log.hidden
    != @user.change_log ? @user.change_log.chomp.gsub("\n","<br>") : "(no changes)"